apiVersion: v2
name: hive
description: hive helm chart
icon: https://upload.wikimedia.org/wikipedia/commons/b/bb/Apache_Hive_logo.svg
type: application
version: 0.3.1
appVersion: 3.1.3
# kubeVersion: ^1.15
dependencies:
- name: postgresql
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
