image:
  repository: hub.teko.vn/data/spark
  tag: 2.4.4-hadoop-3.2.1
  pullPolicy: IfNotPresent

app:
  replicas: 1
  command:
  - spark
  - history-server

env:
  - name: abc
    value: xyz
  - name: foo
    value: bar
  - name: first
    valueFrom:
      configMapKeyRef:
        name: configs
        key: foo
  - name: second
    valueFrom:
      externalSource: true
      configMapKeyRef:
        name: abcxyz
        key: bar
  - name: POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: CPU_LIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.cpu

envFrom:
  - prefix: ENV_
    secretRef:
      name: credential
      optional: true
  - configMapRef:
      name: configs

volumes:
  - name: configs
    configMap:
      name: configs
      optional: true

configMaps:
  - name: configs
    data:
      foo: bar
      abc: xyz
  - name: abcxyz
    data:
      first: 1
      second: 2

secrets:
  - name: credential
    type: Opaque
    stringData:
      username: admin
    data:
      password: Zm9vYmFyCg==  # base64 encoded string
